// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ManualBatch struct {
	ID              string
	State           string
	RemoteID        *string
	ResultsUrl      *string
	ProcessingCount int32
	SucceededCount  int32
	ErroredCount    int32
	CanceledCount   int32
	ExpiredCount    int32
	CreatedAt       pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	AppliedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ManualBatchItem struct {
	CustomID     string
	BatchID      string
	ReadingID    string
	State        string
	ItemIndex    int32
	RequestJson  []byte
	ResultJson   []byte
	ErrorType    *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	SubmittedAt  pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	AppliedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Reading struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	Search          interface{}
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ReadingVector struct {
	ReadingID  string
	Embedding  *pgvector.Vector
	Generation pgtype.Timestamptz
}
