// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReadings = `-- name: CountReadings :one
select count(*)
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
`

type CountReadingsParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
}

func (q *Queries) CountReadings(ctx context.Context, arg CountReadingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReadings, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReading = `-- name: CreateReading :one
insert into readings (
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
) values (
  $1, $2, $3, $4, $5, nullif($6, ''), nullif($7, ''), nullif($8, ''), nullif($9, ''),
  $10, nullif($11, ''), nullif($12, ''), nullif($13, ''), nullif($14, ''), nullif($15, ''),
  $16, $17, $18, $19, $20, $21
) on conflict (url_key) do nothing
returning id
`

type CreateReadingParams struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Column6         interface{}
	Column7         interface{}
	Column8         interface{}
	Column9         interface{}
	WordCount       *int32
	Column11        interface{}
	Column12        interface{}
	Column13        interface{}
	Column14        interface{}
	Column15        interface{}
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (string, error) {
	row := q.db.QueryRow(ctx, createReading,
		arg.ID,
		arg.Url,
		arg.UrlKey,
		arg.Status,
		arg.SourceKind,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.WordCount,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.ProcessAttempts,
		arg.Tags,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteReading = `-- name: DeleteReading :execrows
delete from readings
where id = $1
`

func (q *Queries) DeleteReading(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReading, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReadingByID = `-- name: GetReadingByID :one
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
from readings
where id = $1
`

type GetReadingByIDRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetReadingByID(ctx context.Context, id string) (GetReadingByIDRow, error) {
	row := q.db.QueryRow(ctx, getReadingByID, id)
	var i GetReadingByIDRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlKey,
		&i.Status,
		&i.SourceKind,
		&i.Title,
		&i.Author,
		&i.Site,
		&i.Lang,
		&i.WordCount,
		&i.ExtractionMode,
		&i.ContentKey,
		&i.RawKey,
		&i.Summary,
		&i.Error,
		&i.ProcessAttempts,
		&i.Tags,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingByURLKey = `-- name: GetReadingByURLKey :one
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
from readings
where url_key = $1
`

type GetReadingByURLKeyRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetReadingByURLKey(ctx context.Context, urlKey string) (GetReadingByURLKeyRow, error) {
	row := q.db.QueryRow(ctx, getReadingByURLKey, urlKey)
	var i GetReadingByURLKeyRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlKey,
		&i.Status,
		&i.SourceKind,
		&i.Title,
		&i.Author,
		&i.Site,
		&i.Lang,
		&i.WordCount,
		&i.ExtractionMode,
		&i.ContentKey,
		&i.RawKey,
		&i.Summary,
		&i.Error,
		&i.ProcessAttempts,
		&i.Tags,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNonTerminalReadings = `-- name: ListNonTerminalReadings :many
select id, process_attempts
from readings
where status = 'pending'
   or (status = 'running' and started_at < $1)
`

type ListNonTerminalReadingsRow struct {
	ID              string
	ProcessAttempts int32
}

func (q *Queries) ListNonTerminalReadings(ctx context.Context, startedAt pgtype.Timestamptz) ([]ListNonTerminalReadingsRow, error) {
	rows, err := q.db.Query(ctx, listNonTerminalReadings, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNonTerminalReadingsRow
	for rows.Next() {
		var i ListNonTerminalReadingsRow
		if err := rows.Scan(&i.ID, &i.ProcessAttempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceReadingTags = `-- name: ReplaceReadingTags :execrows
update readings
set tags = $2, updated_at = $3
where id = $1
`

type ReplaceReadingTagsParams struct {
	ID        string
	Tags      []string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ReplaceReadingTags(ctx context.Context, arg ReplaceReadingTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceReadingTags, arg.ID, arg.Tags, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchReadingsNewest = `-- name: SearchReadingsNewest :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (created_at, id) < ($6::timestamptz, $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  created_at desc,
  id desc
limit $8
`

type SearchReadingsNewestParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 pgtype.Timestamptz
	Column7 string
	Limit   int32
}

type SearchReadingsNewestRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsNewest(ctx context.Context, arg SearchReadingsNewestParams) ([]SearchReadingsNewestRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsNewest,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsNewestRow
	for rows.Next() {
		var i SearchReadingsNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchReadingsOldest = `-- name: SearchReadingsOldest :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (created_at, id) > ($6::timestamptz, $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  created_at asc,
  id asc
limit $8
`

type SearchReadingsOldestParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 pgtype.Timestamptz
	Column7 string
	Limit   int32
}

type SearchReadingsOldestRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsOldest(ctx context.Context, arg SearchReadingsOldestParams) ([]SearchReadingsOldestRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsOldest,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsOldestRow
	for rows.Next() {
		var i SearchReadingsOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchReadingsTitle = `-- name: SearchReadingsTitle :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (lower(coalesce(title, '')), id) > (lower($6::text), $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  lower(coalesce(title, '')) asc,
  id asc
limit $8
`

type SearchReadingsTitleParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 string
	Column7 string
	Limit   int32
}

type SearchReadingsTitleRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsTitle(ctx context.Context, arg SearchReadingsTitleParams) ([]SearchReadingsTitleRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsTitle,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsTitleRow
	for rows.Next() {
		var i SearchReadingsTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReadingStatus = `-- name: UpdateReadingStatus :execrows
update readings
set
  status = $2,
  started_at = $3,
  finished_at = $4,
  error = nullif($5, ''),
  process_attempts = $6,
  updated_at = $7
where id = $1
`

type UpdateReadingStatusParams struct {
	ID              string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Column5         interface{}
	ProcessAttempts int32
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateReadingStatus(ctx context.Context, arg UpdateReadingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReadingStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Column5,
		arg.ProcessAttempts,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
