// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveManualBatchItems = `-- name: CountActiveManualBatchItems :one
select count(*)
from manual_batch_items
where batch_id = $1
  and state in ('planned', 'submitted', 'succeeded')
`

func (q *Queries) CountActiveManualBatchItems(ctx context.Context, batchID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveManualBatchItems, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReadings = `-- name: CountReadings :one
select count(*)
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
`

type CountReadingsParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
}

func (q *Queries) CountReadings(ctx context.Context, arg CountReadingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReadings, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManualBatch = `-- name: CreateManualBatch :exec
insert into manual_batches (
  id, state, remote_id, results_url,
  processing_count, succeeded_count, errored_count, canceled_count, expired_count,
  created_at, submitted_at, finished_at, applied_at, updated_at
) values (
  $1, $2, nullif($3, ''), nullif($4, ''),
  $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14
)
`

type CreateManualBatchParams struct {
	ID              string
	State           string
	Column3         interface{}
	Column4         interface{}
	ProcessingCount int32
	SucceededCount  int32
	ErroredCount    int32
	CanceledCount   int32
	ExpiredCount    int32
	CreatedAt       pgtype.Timestamptz
	SubmittedAt     pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	AppliedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateManualBatch(ctx context.Context, arg CreateManualBatchParams) error {
	_, err := q.db.Exec(ctx, createManualBatch,
		arg.ID,
		arg.State,
		arg.Column3,
		arg.Column4,
		arg.ProcessingCount,
		arg.SucceededCount,
		arg.ErroredCount,
		arg.CanceledCount,
		arg.ExpiredCount,
		arg.CreatedAt,
		arg.SubmittedAt,
		arg.FinishedAt,
		arg.AppliedAt,
		arg.UpdatedAt,
	)
	return err
}

const createManualBatchItem = `-- name: CreateManualBatchItem :exec
insert into manual_batch_items (
  custom_id, batch_id, reading_id, state, item_index, request_json, result_json,
  error_type, error_message, created_at, submitted_at, finished_at, applied_at, updated_at
) values (
  $1, $2, $3, $4, $5, $6, $7,
  nullif($8, ''), nullif($9, ''), $10, $11, $12, $13, $14
)
`

type CreateManualBatchItemParams struct {
	CustomID    string
	BatchID     string
	ReadingID   string
	State       string
	ItemIndex   int32
	RequestJson []byte
	ResultJson  []byte
	Column8     interface{}
	Column9     interface{}
	CreatedAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	AppliedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateManualBatchItem(ctx context.Context, arg CreateManualBatchItemParams) error {
	_, err := q.db.Exec(ctx, createManualBatchItem,
		arg.CustomID,
		arg.BatchID,
		arg.ReadingID,
		arg.State,
		arg.ItemIndex,
		arg.RequestJson,
		arg.ResultJson,
		arg.Column8,
		arg.Column9,
		arg.CreatedAt,
		arg.SubmittedAt,
		arg.FinishedAt,
		arg.AppliedAt,
		arg.UpdatedAt,
	)
	return err
}

const createReading = `-- name: CreateReading :one
insert into readings (
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
) values (
  $1, $2, $3, $4, $5, nullif($6, ''), nullif($7, ''), nullif($8, ''), nullif($9, ''),
  $10, nullif($11, ''), nullif($12, ''), nullif($13, ''), nullif($14, ''), $15, $16,
  $17, nullif($18, ''), $19, $20,
  $21, $22, $23, $24
) on conflict (url_key) do nothing
returning id
`

type CreateReadingParams struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Column6         interface{}
	Column7         interface{}
	Column8         interface{}
	Column9         interface{}
	WordCount       *int32
	Column11        interface{}
	Column12        interface{}
	Column13        interface{}
	Column14        interface{}
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Column18        interface{}
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (string, error) {
	row := q.db.QueryRow(ctx, createReading,
		arg.ID,
		arg.Url,
		arg.UrlKey,
		arg.Status,
		arg.SourceKind,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.WordCount,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.SummaryJson,
		arg.SimilarJson,
		arg.DiagnosticsJson,
		arg.Column18,
		arg.ProcessAttempts,
		arg.Tags,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteReading = `-- name: DeleteReading :execrows
delete from readings
where id = $1
`

func (q *Queries) DeleteReading(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReading, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManualBatch = `-- name: GetManualBatch :one
select
  id, state, remote_id, results_url,
  processing_count, succeeded_count, errored_count, canceled_count, expired_count,
  created_at, submitted_at, finished_at, applied_at, updated_at
from manual_batches
where id = $1
`

func (q *Queries) GetManualBatch(ctx context.Context, id string) (ManualBatch, error) {
	row := q.db.QueryRow(ctx, getManualBatch, id)
	var i ManualBatch
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.RemoteID,
		&i.ResultsUrl,
		&i.ProcessingCount,
		&i.SucceededCount,
		&i.ErroredCount,
		&i.CanceledCount,
		&i.ExpiredCount,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManualBatchItemByCustomID = `-- name: GetManualBatchItemByCustomID :one
select
  custom_id, batch_id, reading_id, state, item_index, request_json, result_json,
  error_type, error_message, created_at, submitted_at, finished_at, applied_at, updated_at
from manual_batch_items
where custom_id = $1
`

func (q *Queries) GetManualBatchItemByCustomID(ctx context.Context, customID string) (ManualBatchItem, error) {
	row := q.db.QueryRow(ctx, getManualBatchItemByCustomID, customID)
	var i ManualBatchItem
	err := row.Scan(
		&i.CustomID,
		&i.BatchID,
		&i.ReadingID,
		&i.State,
		&i.ItemIndex,
		&i.RequestJson,
		&i.ResultJson,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingByID = `-- name: GetReadingByID :one
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
from readings
where id = $1
`

type GetReadingByIDRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetReadingByID(ctx context.Context, id string) (GetReadingByIDRow, error) {
	row := q.db.QueryRow(ctx, getReadingByID, id)
	var i GetReadingByIDRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlKey,
		&i.Status,
		&i.SourceKind,
		&i.Title,
		&i.Author,
		&i.Site,
		&i.Lang,
		&i.WordCount,
		&i.ExtractionMode,
		&i.ContentKey,
		&i.RawKey,
		&i.Summary,
		&i.SummaryJson,
		&i.SimilarJson,
		&i.DiagnosticsJson,
		&i.Error,
		&i.ProcessAttempts,
		&i.Tags,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingByURLKey = `-- name: GetReadingByURLKey :one
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at
from readings
where url_key = $1
`

type GetReadingByURLKeyRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetReadingByURLKey(ctx context.Context, urlKey string) (GetReadingByURLKeyRow, error) {
	row := q.db.QueryRow(ctx, getReadingByURLKey, urlKey)
	var i GetReadingByURLKeyRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlKey,
		&i.Status,
		&i.SourceKind,
		&i.Title,
		&i.Author,
		&i.Site,
		&i.Lang,
		&i.WordCount,
		&i.ExtractionMode,
		&i.ContentKey,
		&i.RawKey,
		&i.Summary,
		&i.SummaryJson,
		&i.SimilarJson,
		&i.DiagnosticsJson,
		&i.Error,
		&i.ProcessAttempts,
		&i.Tags,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManualBatchItems = `-- name: ListManualBatchItems :many
select
  custom_id, batch_id, reading_id, state, item_index, request_json, result_json,
  error_type, error_message, created_at, submitted_at, finished_at, applied_at, updated_at
from manual_batch_items
where batch_id = $1
order by item_index asc
`

func (q *Queries) ListManualBatchItems(ctx context.Context, batchID string) ([]ManualBatchItem, error) {
	rows, err := q.db.Query(ctx, listManualBatchItems, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualBatchItem
	for rows.Next() {
		var i ManualBatchItem
		if err := rows.Scan(
			&i.CustomID,
			&i.BatchID,
			&i.ReadingID,
			&i.State,
			&i.ItemIndex,
			&i.RequestJson,
			&i.ResultJson,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.FinishedAt,
			&i.AppliedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualBatches = `-- name: ListManualBatches :many
select
  id, state, remote_id, results_url,
  processing_count, succeeded_count, errored_count, canceled_count, expired_count,
  created_at, submitted_at, finished_at, applied_at, updated_at
from manual_batches
where ($1 = '' or state = $1)
  and (not $2::boolean or state in ('planned', 'submitted', 'results_ready'))
order by created_at desc, id desc
`

type ListManualBatchesParams struct {
	Column1 interface{}
	Column2 bool
}

func (q *Queries) ListManualBatches(ctx context.Context, arg ListManualBatchesParams) ([]ManualBatch, error) {
	rows, err := q.db.Query(ctx, listManualBatches, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualBatch
	for rows.Next() {
		var i ManualBatch
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.RemoteID,
			&i.ResultsUrl,
			&i.ProcessingCount,
			&i.SucceededCount,
			&i.ErroredCount,
			&i.CanceledCount,
			&i.ExpiredCount,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.FinishedAt,
			&i.AppliedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonTerminalReadings = `-- name: ListNonTerminalReadings :many
select id, process_attempts
from readings
where status = 'pending'
   or (status = 'running' and started_at < $1)
`

type ListNonTerminalReadingsRow struct {
	ID              string
	ProcessAttempts int32
}

func (q *Queries) ListNonTerminalReadings(ctx context.Context, startedAt pgtype.Timestamptz) ([]ListNonTerminalReadingsRow, error) {
	rows, err := q.db.Query(ctx, listNonTerminalReadings, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNonTerminalReadingsRow
	for rows.Next() {
		var i ListNonTerminalReadingsRow
		if err := rows.Scan(&i.ID, &i.ProcessAttempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManualBatchItemApplied = `-- name: MarkManualBatchItemApplied :execrows
update manual_batch_items
set
  state = 'applied',
  applied_at = $2,
  updated_at = $2
where custom_id = $1
  and state = 'succeeded'
`

type MarkManualBatchItemAppliedParams struct {
	CustomID  string
	AppliedAt pgtype.Timestamptz
}

func (q *Queries) MarkManualBatchItemApplied(ctx context.Context, arg MarkManualBatchItemAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markManualBatchItemApplied, arg.CustomID, arg.AppliedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceReadingTags = `-- name: ReplaceReadingTags :execrows
update readings
set tags = $2, updated_at = $3
where id = $1
  and ($4::timestamptz is null or (status = 'running' and started_at = $4))
`

type ReplaceReadingTagsParams struct {
	ID        string
	Tags      []string
	UpdatedAt pgtype.Timestamptz
	Column4   pgtype.Timestamptz
}

func (q *Queries) ReplaceReadingTags(ctx context.Context, arg ReplaceReadingTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceReadingTags,
		arg.ID,
		arg.Tags,
		arg.UpdatedAt,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reprocessReading = `-- name: ReprocessReading :execrows
update readings
set
  status = 'pending',
  title = nullif($3, ''),
  author = null,
  site = null,
  lang = null,
  word_count = null,
  extraction_mode = null,
  content_key = null,
  raw_key = nullif($2, ''),
  summary = null,
  summary_json = null,
  similar_json = null,
  diagnostics_json = null,
  error = null,
  process_attempts = 0,
  started_at = null,
  finished_at = null,
  updated_at = $4
where id = $1
`

type ReprocessReadingParams struct {
	ID        string
	Column2   interface{}
	Column3   interface{}
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ReprocessReading(ctx context.Context, arg ReprocessReadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, reprocessReading,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchReadingsNewest = `-- name: SearchReadingsNewest :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (created_at, id) < ($6::timestamptz, $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  created_at desc,
  id desc
limit $8
`

type SearchReadingsNewestParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 pgtype.Timestamptz
	Column7 string
	Limit   int32
}

type SearchReadingsNewestRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsNewest(ctx context.Context, arg SearchReadingsNewestParams) ([]SearchReadingsNewestRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsNewest,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsNewestRow
	for rows.Next() {
		var i SearchReadingsNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.SummaryJson,
			&i.SimilarJson,
			&i.DiagnosticsJson,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchReadingsOldest = `-- name: SearchReadingsOldest :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (created_at, id) > ($6::timestamptz, $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  created_at asc,
  id asc
limit $8
`

type SearchReadingsOldestParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 pgtype.Timestamptz
	Column7 string
	Limit   int32
}

type SearchReadingsOldestRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsOldest(ctx context.Context, arg SearchReadingsOldestParams) ([]SearchReadingsOldestRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsOldest,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsOldestRow
	for rows.Next() {
		var i SearchReadingsOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.SummaryJson,
			&i.SimilarJson,
			&i.DiagnosticsJson,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchReadingsTitle = `-- name: SearchReadingsTitle :many
select
  id, url, url_key, status, source_kind, title, author, site, lang, word_count,
  extraction_mode, content_key, raw_key, summary, summary_json, similar_json,
  diagnostics_json, error, process_attempts, tags,
  created_at, started_at, finished_at, updated_at,
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end as search_rank
from readings
where ($1 = '' or search @@ websearch_to_tsquery('english', $1))
  and (cardinality($2::text[]) = 0 or tags @> $2::text[])
  and ($3 = '' or status = $3)
  and (
    not $4::boolean
    or case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end < $5::real
    or (
      case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end = $5::real
      and (lower(coalesce(title, '')), id) > (lower($6::text), $7::text)
    )
  )
order by
  case when $1 <> '' then ts_rank(search, websearch_to_tsquery('english', $1)) else 0::real end desc,
  lower(coalesce(title, '')) asc,
  id asc
limit $8
`

type SearchReadingsTitleParams struct {
	Column1 interface{}
	Column2 []string
	Column3 interface{}
	Column4 bool
	Column5 float32
	Column6 string
	Column7 string
	Limit   int32
}

type SearchReadingsTitleRow struct {
	ID              string
	Url             string
	UrlKey          string
	Status          string
	SourceKind      string
	Title           *string
	Author          *string
	Site            *string
	Lang            *string
	WordCount       *int32
	ExtractionMode  *string
	ContentKey      *string
	RawKey          *string
	Summary         *string
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	Error           *string
	ProcessAttempts int32
	Tags            []string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SearchRank      float32
}

func (q *Queries) SearchReadingsTitle(ctx context.Context, arg SearchReadingsTitleParams) ([]SearchReadingsTitleRow, error) {
	rows, err := q.db.Query(ctx, searchReadingsTitle,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReadingsTitleRow
	for rows.Next() {
		var i SearchReadingsTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlKey,
			&i.Status,
			&i.SourceKind,
			&i.Title,
			&i.Author,
			&i.Site,
			&i.Lang,
			&i.WordCount,
			&i.ExtractionMode,
			&i.ContentKey,
			&i.RawKey,
			&i.Summary,
			&i.SummaryJson,
			&i.SimilarJson,
			&i.DiagnosticsJson,
			&i.Error,
			&i.ProcessAttempts,
			&i.Tags,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitManualBatch = `-- name: SubmitManualBatch :execrows
update manual_batches
set
  state = 'submitted',
  remote_id = nullif($2, ''),
  results_url = nullif($3, ''),
  processing_count = $4,
  succeeded_count = $5,
  errored_count = $6,
  canceled_count = $7,
  expired_count = $8,
  submitted_at = $9,
  updated_at = $9
where id = $1
  and state = 'planned'
  and submitted_at is null
`

type SubmitManualBatchParams struct {
	ID              string
	Column2         interface{}
	Column3         interface{}
	ProcessingCount int32
	SucceededCount  int32
	ErroredCount    int32
	CanceledCount   int32
	ExpiredCount    int32
	SubmittedAt     pgtype.Timestamptz
}

func (q *Queries) SubmitManualBatch(ctx context.Context, arg SubmitManualBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitManualBatch,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.ProcessingCount,
		arg.SucceededCount,
		arg.ErroredCount,
		arg.CanceledCount,
		arg.ExpiredCount,
		arg.SubmittedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitManualBatchItems = `-- name: SubmitManualBatchItems :execrows
update manual_batch_items
set
  state = 'submitted',
  submitted_at = $2,
  updated_at = $2
where batch_id = $1
  and state = 'planned'
`

type SubmitManualBatchItemsParams struct {
	BatchID     string
	SubmittedAt pgtype.Timestamptz
}

func (q *Queries) SubmitManualBatchItems(ctx context.Context, arg SubmitManualBatchItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitManualBatchItems, arg.BatchID, arg.SubmittedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateManualBatchActiveItemsTerminal = `-- name: UpdateManualBatchActiveItemsTerminal :execrows
update manual_batch_items
set
  state = $2,
  finished_at = $3,
  updated_at = $3
where batch_id = $1
  and state in ('planned', 'submitted', 'succeeded')
`

type UpdateManualBatchActiveItemsTerminalParams struct {
	BatchID    string
	State      string
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) UpdateManualBatchActiveItemsTerminal(ctx context.Context, arg UpdateManualBatchActiveItemsTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateManualBatchActiveItemsTerminal, arg.BatchID, arg.State, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateManualBatchState = `-- name: UpdateManualBatchState :execrows
update manual_batches
set
  state = $2,
  results_url = coalesce(nullif($3, ''), results_url),
  processing_count = $4,
  succeeded_count = $5,
  errored_count = $6,
  canceled_count = $7,
  expired_count = $8,
  finished_at = $9,
  applied_at = $10,
  updated_at = $11
where id = $1
  and state = $12
`

type UpdateManualBatchStateParams struct {
	ID              string
	State           string
	Column3         interface{}
	ProcessingCount int32
	SucceededCount  int32
	ErroredCount    int32
	CanceledCount   int32
	ExpiredCount    int32
	FinishedAt      pgtype.Timestamptz
	AppliedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	State_2         string
}

func (q *Queries) UpdateManualBatchState(ctx context.Context, arg UpdateManualBatchStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateManualBatchState,
		arg.ID,
		arg.State,
		arg.Column3,
		arg.ProcessingCount,
		arg.SucceededCount,
		arg.ErroredCount,
		arg.CanceledCount,
		arg.ExpiredCount,
		arg.FinishedAt,
		arg.AppliedAt,
		arg.UpdatedAt,
		arg.State_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReadingContent = `-- name: UpdateReadingContent :execrows
update readings
set
  title = nullif($2, ''),
  author = nullif($3, ''),
  site = nullif($4, ''),
  lang = nullif($5, ''),
  word_count = $6,
  extraction_mode = nullif($7, ''),
  content_key = nullif($8, ''),
  raw_key = nullif($9, ''),
  summary = nullif($10, ''),
  summary_json = $11,
  similar_json = $12,
  diagnostics_json = $13,
  updated_at = $14
where id = $1
  and ($15::timestamptz is null or (status = 'running' and started_at = $15))
`

type UpdateReadingContentParams struct {
	ID              string
	Column2         interface{}
	Column3         interface{}
	Column4         interface{}
	Column5         interface{}
	WordCount       *int32
	Column7         interface{}
	Column8         interface{}
	Column9         interface{}
	Column10        interface{}
	SummaryJson     []byte
	SimilarJson     []byte
	DiagnosticsJson []byte
	UpdatedAt       pgtype.Timestamptz
	Column15        pgtype.Timestamptz
}

func (q *Queries) UpdateReadingContent(ctx context.Context, arg UpdateReadingContentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReadingContent,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.WordCount,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.SummaryJson,
		arg.SimilarJson,
		arg.DiagnosticsJson,
		arg.UpdatedAt,
		arg.Column15,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReadingImport = `-- name: UpdateReadingImport :execrows
update readings
set
  status = 'pending',
  source_kind = $2,
  title = nullif($3, ''),
  author = null,
  site = null,
  lang = null,
  word_count = null,
  extraction_mode = null,
  content_key = null,
  raw_key = nullif($4, ''),
  summary = null,
  summary_json = null,
  similar_json = null,
  diagnostics_json = null,
  error = null,
  process_attempts = 0,
  tags = $5,
  started_at = null,
  finished_at = null,
  updated_at = $6
where id = $1
`

type UpdateReadingImportParams struct {
	ID         string
	SourceKind string
	Column3    interface{}
	Column4    interface{}
	Tags       []string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateReadingImport(ctx context.Context, arg UpdateReadingImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReadingImport,
		arg.ID,
		arg.SourceKind,
		arg.Column3,
		arg.Column4,
		arg.Tags,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReadingStatus = `-- name: UpdateReadingStatus :execrows
update readings
set
  status = $2,
  started_at = $3,
  finished_at = $4,
  error = nullif($5, ''),
  process_attempts = $6,
  updated_at = $7
where id = $1
`

type UpdateReadingStatusParams struct {
	ID              string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Column5         interface{}
	ProcessAttempts int32
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateReadingStatus(ctx context.Context, arg UpdateReadingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReadingStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Column5,
		arg.ProcessAttempts,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writeManualBatchItemResult = `-- name: WriteManualBatchItemResult :execrows
update manual_batch_items
set
  state = $2,
  result_json = $3,
  error_type = nullif($4, ''),
  error_message = nullif($5, ''),
  finished_at = $6,
  updated_at = $6
where custom_id = $1
  and state = 'submitted'
  and finished_at is null
`

type WriteManualBatchItemResultParams struct {
	CustomID   string
	State      string
	ResultJson []byte
	Column4    interface{}
	Column5    interface{}
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) WriteManualBatchItemResult(ctx context.Context, arg WriteManualBatchItemResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, writeManualBatchItemResult,
		arg.CustomID,
		arg.State,
		arg.ResultJson,
		arg.Column4,
		arg.Column5,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
